name: Increment Build Number

on:
    pull_request:
      types:
        - closed
      branches:
        - main
    workflow_dispatch:

jobs:
  increment-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Increment build number
        run: |
          # Read current build number
          current_build=$(cat build)
          
          # Increment build number
          new_build=$((current_build + 1))
          
          # Update build file
          echo $new_build > build
    
      - name: Publish changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-increment build'
          default_author: github_actions
          add: 'build'